#El base href del index.html debe ser =/ris

version: '3'

services:
  web:
    image: nginx
    container_name: risA
    ports:
    - "4200:80"
    volumes:
    - ./dist/ris:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
